version: '3'

services:
  nginx:
    depends_on:
      - web
    image: 'nginx:latest'
    ports: 
      - ${NGINX_PORT:-8080}:80
    volumes:
      - ./nginx:/etc/nginx
    environment:
      - NGINX_PORT=${NGINX_PORT:-8080}

  web:
    depends_on:
      - database
      - redis
    build: rails
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - ./rails:/srv/coral
      - gem_cache:/var/lib/ruby/gems
    env_file:
      - .env/development/database
      - .env/development/web
      - .env/development/storage

  storage:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes: 
      - imagedata:/srv/data
    command: server /srv/data
    env_file:
      - .env/development/storage

  redis:
    image: redis

  database:
    image: postgres
    env_file:
      - .env/development/database
    volumes:
      - coral_data:/var/lib/postgresql/data

volumes:
  coral_data:
  gem_cache:
  imagedata:
