version: '3'

services:
  webpacker_dev:
    build: rails
    command: ./bin/webpack-dev-server
    ports:
      - "3035:3035"
    volumes:
      - ./rails:/srv/coral
      - gem_cache:/var/lib/ruby/gems
    env_file:
      - .env/development/database
      - .env/development/web
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

volumes:
  gem_cache:
